// GET DETAILS FILM
const GET_DETAILS_FILM = 'movie/GET_DETAILS_FILM';
const GET_SUCCESS = 'movie/GET_SUCCESS';
const ADD_COMMENT = 'movie/ADD_COMMENT';

export default {
    GET_DETAILS_FILM,
    GET_SUCCESS,
    ADD_COMMENT
};
